(function(){
  "use strict";
  const app=document.getElementById("app"),questions=window.QUESTIONS;
  let state={stage:"intro",name:"",index:0,answers:{},startedAt:0,submitted:"idle"};
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const upper=()=>state.name.trim().length>0&&state.name.trim()===state.name.trim().toLocaleUpperCase("pt-BR");
  const scores=()=>{const byLevel=[1,2,3].map(l=>questions.filter(q=>q.level===l&&state.answers[q.id]===q.answer).length),qs=byLevel.reduce((a,b)=>a+b,0);return{byLevel,questionsScore:qs,total:qs+(upper()?1:0)}};
  function render(){const q=questions[state.index],level=q?q.level:1;if(state.stage==="intro")app.innerHTML=`<section class="card intro-card"><div class="eyebrow">AVALIAÇÃO DIAGNÓSTICA</div><h1>Leia tudo antes de começar.</h1><p class="lead">Você responderá a 30 questões de programação em JavaScript, organizadas em três níveis de dificuldade. Há apenas uma resposta correta por questão.</p><div class="instructions"><h2>Instruções importantes</h2><ul><li>O simulado vale <strong>31 pontos</strong>: 30 questões e 1 ponto de atenção.</li><li>Responda sem consultar outros materiais.</li><li>Você não poderá voltar às questões anteriores.</li><li><strong>Para conquistar o ponto de atenção, escreva seu nome completo usando TODAS AS LETRAS MAIÚSCULAS.</strong></li></ul></div><label class="name-label">Nome completo<input id="student-name" value="${esc(state.name)}" placeholder="Digite seu nome completo" autocomplete="name"></label><button id="start" class="primary" ${state.name.trim()?"":"disabled"}>INICIAR TESTE <span>→</span></button></section>`;
    else if(state.stage==="level"||state.stage==="transition"){const desc=level===1?"Fundamentos: variáveis, tipos de dados, operadores e sequência de comandos.":level===2?"Aplicação: decisões, operadores lógicos, repetições e depuração.":"Desafio: funções, vetores, laços combinados e resolução de problemas.";app.innerHTML=`<section class="card level-card"><div class="level-number level-${level}">${level}</div><div class="eyebrow">${state.stage==="level"?"PREPARE-SE":"ETAPA CONCLUÍDA"}</div><h1>Você fará agora as questões de Nível ${level}</h1><p>${desc}</p><div class="level-meta"><span>10 questões</span><span>1 ponto cada</span><span>uma por tela</span></div><button id="begin-level" class="primary">COMEÇAR NÍVEL ${level} <span>→</span></button></section>`}
    else if(state.stage==="quiz"){app.innerHTML=`<section class="quiz-wrap"><div class="progress-head"><span>Nível ${q.level}</span><span>Questão ${q.id} de 30</span></div><div class="progress"><i style="width:${q.id/30*100}%"></i></div><article class="card question-card"><div class="skill-tag">${esc(q.skill)}</div><h1>${esc(q.prompt)}</h1>${q.code?`<pre><code>${esc(q.code)}</code></pre>`:""}<div class="options">${q.options.map((o,i)=>`<button data-option="${i}" class="${state.answers[q.id]===i?"selected":""}"><b>${String.fromCharCode(65+i)}</b><span>${esc(o)}</span></button>`).join("")}</div><div class="question-footer"><span>Escolha uma alternativa para avançar.</span><button id="next" class="primary compact" ${state.answers[q.id]===undefined?"disabled":""}>${q.id===30?"FINALIZAR":"PRÓXIMA"} <span>→</span></button></div></article></section>`}
    else renderResult();bind();window.scrollTo({top:0,behavior:"smooth"})}
  function renderResult(){const s=scores();app.innerHTML=`<section class="result-wrap"><section class="card result-hero"><div class="eyebrow">SIMULADO CONCLUÍDO</div><h1>${esc(state.name.trim())}, este é o seu resultado.</h1><div class="score-circle"><strong>${s.total}</strong><span>de 31 pontos</span></div><p>${s.total>=25?"Excelente domínio! Você está pronta para desafios mais avançados.":s.total>=18?"Bom resultado! Revise os temas indicados no gabarito.":"Este diagnóstico mostrou onde concentrar seus estudos. Errar aqui faz parte do treino."}</p><div id="send-status" class="send-status ${state.submitted}">${state.submitted==="sent"?"✓ Resultado enviado para a professora.":state.submitted==="error"?"Resultado exibido. O envio à planilha ainda precisa ser configurado.":"Salvando resultado…"}</div></section><div class="score-grid">${s.byLevel.map((x,i)=>`<div class="mini-card"><span>Nível ${i+1}</span><strong>${x}/10</strong></div>`).join("")}<div class="mini-card attention"><span>Ponto de atenção</span><strong>${upper()?"1/1":"0/1"}</strong><small>${upper()?"Nome em maiúsculas ✓":"A instrução do nome passou despercebida."}</small></div></div><section class="card review"><h2>Gabarito individual</h2><p>Confira sua resposta e a explicação de cada questão.</p>${questions.map(q=>{const a=state.answers[q.id],ok=a===q.answer;return`<details class="${ok?"correct":"wrong"}"><summary><span>Questão ${q.id} • ${esc(q.skill)}</span><b>${ok?"✓ Acertou":"✕ Errou"}</b></summary><div><p><strong>Sua resposta:</strong> ${a===undefined?"Não respondida":`${String.fromCharCode(65+a)}) ${esc(q.options[a])}`}</p><p><strong>Resposta correta:</strong> ${String.fromCharCode(65+q.answer)}) ${esc(q.options[q.answer])}</p><p>${esc(q.explanation)}</p></div></details>`}).join("")}</section><button id="print" class="secondary">IMPRIMIR RESULTADO</button><button id="restart" class="text-button">Refazer simulado</button></section>`;if(state.submitted==="idle")sendResult()}
  function bind(){const name=document.getElementById("student-name");if(name)name.addEventListener("input",e=>{state.name=e.target.value;document.getElementById("start").disabled=!state.name.trim()});document.getElementById("start")?.addEventListener("click",()=>{state.startedAt=Date.now();state.stage="level";render()});document.getElementById("begin-level")?.addEventListener("click",()=>{state.stage="quiz";render()});document.querySelectorAll("[data-option]").forEach(b=>b.addEventListener("click",()=>{state.answers[questions[state.index].id]=Number(b.dataset.option);render()}));document.getElementById("next")?.addEventListener("click",next);document.getElementById("print")?.addEventListener("click",()=>window.print());document.getElementById("restart")?.addEventListener("click",()=>{state={stage:"intro",name:"",index:0,answers:{},startedAt:0,submitted:"idle"};render()})}
  function next(){if(state.index===questions.length-1){state.stage="result";render();return}const old=questions[state.index].level;state.index++;state.stage=questions[state.index].level!==old?"transition":"quiz";render()}
  async function sendResult(){const url=window.RESULTS_URL||"";if(!url||url.includes("COLE_AQUI")){state.submitted="error";updateStatus();return}state.submitted="sending";updateStatus();const s=scores(),payload={nome:state.name.trim(),regraNome:upper()?"ACERTOU":"ERROU",nivel1:s.byLevel[0],nivel2:s.byLevel[1],nivel3:s.byLevel[2],acertosQuestoes:s.questionsScore,pontuacaoTotal:s.total,duracaoSegundos:Math.round((Date.now()-state.startedAt)/1000),respostas:questions.map(q=>({questao:q.id,respostaAluno:state.answers[q.id]??null,correta:q.answer,acertou:state.answers[q.id]===q.answer}))};try{await fetch(url,{method:"POST",mode:"no-cors",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(payload)});state.submitted="sent"}catch(e){state.submitted="error"}updateStatus()}
  function updateStatus(){const el=document.getElementById("send-status");if(!el)return;el.className=`send-status ${state.submitted}`;el.textContent=state.submitted==="sent"?"✓ Resultado enviado para a professora.":state.submitted==="error"?"Resultado exibido. O envio à planilha ainda precisa ser configurado.":"Salvando resultado…"}
  render();
})();
