window.QUESTIONS = [
  {level:1,topic:"Adicionando outras formas",q:"Qual comando costuma desenhar um círculo?",o:["circle()","square()","line()","text()"],a:0},
  {level:1,topic:"Adicionando outras formas",q:"Para desenhar um retângulo, normalmente informamos...",o:["somente a cor","posição, largura e altura","somente o nome","somente um ângulo"],a:1},
  {level:1,topic:"Colorindo nosso desenho",q:"Qual comando define a cor de preenchimento?",o:["fill()","print()","erase()","mouse()"],a:0},
  {level:1,topic:"Colorindo nosso desenho",q:"Quais são as cores básicas do sistema RGB?",o:["Rosa, cinza e bege","Vermelho, verde e azul","Amarelo, preto e branco","Laranja, roxo e marrom"],a:1},
  {level:1,topic:"Efeito Monalisa",q:"Para fazer os olhos acompanharem o ponteiro, usamos principalmente a posição do...",o:["teclado","monitor","mouse","arquivo"],a:2},
  {level:1,topic:"Novo projeto: quente frio",q:"No jogo Quente e Frio, a dica “quente” significa que o jogador está...",o:["perto do alvo","longe do alvo","sem pontuação","fora do programa"],a:0},
  {level:1,topic:"Será que podemos utilizar Pitágoras?",q:"O teorema de Pitágoras é aplicado em triângulos...",o:["equiláteros","retângulos","obtusângulos","sem lados"],a:1},
  {level:1,topic:"Comandos em JavaScript",q:"Qual palavra-chave cria uma variável cujo valor pode mudar?",o:["let","draw","color","mouse"],a:0},
  {level:1,topic:"Comandos em JavaScript",q:"Qual símbolo inicia um comentário de uma linha?",o:["##","//","**","@@"],a:1},
  {level:1,topic:"Quente frio dinâmico",q:"Um projeto é dinâmico quando...",o:["fica sempre igual","responde às ações do usuário","não possui código","só funciona impresso"],a:1},

  {level:2,topic:"Adicionando outras formas",q:"Em circle(150, 90, 40), os dois primeiros números representam...",o:["a cor","as coordenadas x e y","o tamanho da tela","os cliques"],a:1},
  {level:2,topic:"Adicionando outras formas",q:"Qual comando desenha uma linha de (10,20) até (80,90)?",o:["line(10,20,80,90)","line(10+20)","rect(10,20)","fill(80,90)"],a:0},
  {level:2,topic:"Colorindo nosso desenho",q:"Que cor resulta de fill(255, 0, 0)?",o:["Azul","Verde","Vermelho","Preto"],a:2},
  {level:2,topic:"Colorindo nosso desenho",q:"Qual comando altera apenas o contorno das formas?",o:["stroke()","circle()","background()","random()"],a:0},
  {level:2,topic:"Efeito Monalisa",q:"Se mouseX aumenta, o ponteiro se move principalmente para...",o:["a esquerda","a direita","cima","fora da tela"],a:1},
  {level:2,topic:"Novo projeto: quente frio",q:"Qual recurso escolhe uma posição secreta diferente em cada partida?",o:["random()","text()","stroke()","console.log()"],a:0},
  {level:2,topic:"Será que podemos utilizar Pitágoras?",q:"Num triângulo retângulo com catetos 3 e 4, a hipotenusa mede...",o:["5","6","7","12"],a:0},
  {level:2,topic:"Comandos em JavaScript",q:"Qual estrutura executa um bloco somente quando a condição é verdadeira?",o:["if","fill","circle","let"],a:0},
  {level:2,topic:"Comandos em JavaScript",q:"Qual operador compara igualdade estrita em JavaScript?",o:["=","==","===","=>"],a:2},
  {level:2,topic:"Quente frio dinâmico",q:"Para atualizar continuamente a distância entre mouse e alvo, o cálculo ocorre...",o:["antes do jogo","a cada atualização do desenho","após fechar a página","somente ao imprimir"],a:1},

  {level:3,topic:"Adicionando outras formas",q:"Qual chamada centraliza um círculo de diâmetro 30 no mouse?",o:["circle(mouseX,mouseY,30)","circle(30,30,mouseX)","fill(mouseX,mouseY)","line(mouseX)"],a:0},
  {level:3,topic:"Colorindo nosso desenho",q:"Para a cor variar conforme o mouse se move horizontalmente, devemos...",o:["fixar o RGB","relacionar mouseX aos valores RGB","apagar draw()","usar somente texto"],a:1},
  {level:3,topic:"Efeito Monalisa",q:"Para manter as pupilas dentro dos olhos, é preciso...",o:["aumentar coordenadas sem limite","limitar o deslocamento máximo","remover mouseX e mouseY","desenhar quadrados"],a:1},
  {level:3,topic:"Novo projeto: quente frio",q:"O alvo está em (100,100) e o mouse em (100,140). Qual é a distância?",o:["20","40","100","240"],a:1},
  {level:3,topic:"Será que podemos utilizar Pitágoras?",q:"Qual é a distância entre (0,0) e (6,8)?",o:["7","10","12","14"],a:1},
  {level:3,topic:"Será que podemos utilizar Pitágoras?",q:"Qual expressão calcula a distância entre dois pontos?",o:["√((x₂−x₁)²+(y₂−y₁)²)","x₁+x₂+y₁+y₂","(x₂−x₁)+(y₂−y₁)","x₁·x₂·y₁·y₂"],a:0},
  {level:3,topic:"Comandos em JavaScript",q:"O que faz: if (d < 50) { mensagem = 'Quente'; }?",o:["Mostra Quente se d for menor que 50","Sempre mostra Quente","Apaga d","Cria círculo de raio 50"],a:0},
  {level:3,topic:"Comandos em JavaScript",q:"Qual condição detecta um clique dentro de um círculo de raio 25?",o:["dist(mouseX,mouseY,x,y) < 25","mouseX + mouseY === 25","x > 25 && y > 25","circle === mouse"],a:0},
  {level:3,topic:"Quente frio dinâmico",q:"Se a distância cai de 120 para 45, o feedback deve mudar...",o:["de quente para frio","de frio para quente","de perto para longe","não deve mudar"],a:1},
  {level:3,topic:"Quente frio dinâmico",q:"Para o jogo funcionar em telas diferentes, a posição aleatória deve considerar...",o:["largura e altura da tela","somente o fundo","o nome do aluno","o tamanho da fonte"],a:0}
];
